/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.sareecenter.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.synth.SynthOptionPaneUI;
import javax.swing.table.DefaultTableModel;
import lk.ijse.sareecenter.common.IDGenarator;
import lk.ijse.sareecenter.controller.GRNPaymentsController;
import lk.ijse.sareecenter.controller.PaymentController;
import lk.ijse.sareecenter.dto.GRNPaymentsDTO;
import lk.ijse.sareecenter.dto.PaymentDTO;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author User
 */
public class PanelSupplierPayments extends javax.swing.JPanel {

    /**
     * Creates new form SupplierPayments
     */
    public PanelSupplierPayments() {
        initComponents();
        setSelectType();
        tblGRNPayments.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (tblGRNPayments.getSelectedRow() == -1) {
                    return;
                }

                txtGRNPaymentID.setText(tblGRNPayments.getValueAt(tblGRNPayments.getSelectedRow(), 0).toString());
                txtGRNPaymentDate.setText(tblGRNPayments.getValueAt(tblGRNPayments.getSelectedRow(), 1).toString());
                txtGRNID.setText(tblGRNPayments.getValueAt(tblGRNPayments.getSelectedRow(), 2).toString());
                txtTotalPrice.setText(tblGRNPayments.getValueAt(tblGRNPayments.getSelectedRow(), 3).toString());
                txtTotalQty.setText(tblGRNPayments.getValueAt(tblGRNPayments.getSelectedRow(), 4).toString());

            }
        });

    }

    private void setSelectType() {
        cmbSelectType.removeAllItems();
        cmbSelectType.addItem("GRN Payment ID");
        cmbSelectType.addItem("GRN ID");
        cmbSelectType.addItem("GRN Payment Date");
        AutoCompleteDecorator.decorate(cmbSelectType);
    }

    private void setSelectedTypeItems() throws Exception {
        if (cmbSelectType.getSelectedItem() == "GRN Payment ID") {
            setGRNPaymentIDs();
        } else if (cmbSelectType.getSelectedItem() == "GRN ID") {
            setGRNIDs();
        } else if (cmbSelectType.getSelectedItem() == "GRN Payment Date") {
            setGRNPaymentDates();
        }
    }

    private void setGRNIDs() throws Exception {
        ArrayList<GRNPaymentsDTO> allGRNPayments = GRNPaymentsController.getAllGRNPayments();
        cmbSelectItem.removeAllItems();

        if (allGRNPayments == null) {
            return;
        }
        for (GRNPaymentsDTO payments : allGRNPayments) {

            cmbSelectItem.addItem(payments.getGrnID());

        }
        AutoCompleteDecorator.decorate(cmbSelectItem);

    }

    private void setGRNPaymentDates() throws Exception {
        ArrayList<GRNPaymentsDTO> allGRNPayments = GRNPaymentsController.getAllGRNPayments();
        cmbSelectItem.removeAllItems();

        if (allGRNPayments == null) {
            return;
        }
        for (GRNPaymentsDTO payments : allGRNPayments) {

            cmbSelectItem.addItem(payments.getpDate().toString());

        }
        AutoCompleteDecorator.decorate(cmbSelectItem);

    }

    private void setGRNPaymentIDs() throws Exception {
        ArrayList<GRNPaymentsDTO> allGRNPayments = GRNPaymentsController.getAllGRNPayments();
        cmbSelectItem.removeAllItems();

        if (allGRNPayments == null) {
            return;
        }
        for (GRNPaymentsDTO payments : allGRNPayments) {

            cmbSelectItem.addItem(payments.getGrnPID());

        }
        AutoCompleteDecorator.decorate(cmbSelectItem);

    }

    private void clearAllTexts() {
        txtGRNPaymentID.setText("");
        txtGRNPaymentDate.setText("");
        txtGRNID.setText("");
        txtTotalPrice.setText("");
        txtTotalQty.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnRefresh1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGRNPayments = new org.jdesktop.swingx.JXTable();
        cmbSelectItem = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cmbSelectType = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnCancel1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtGRNPaymentID = new org.jdesktop.swingx.JXTextField();
        txtGRNPaymentDate = new org.jdesktop.swingx.JXTextField();
        txtGRNID = new org.jdesktop.swingx.JXTextField();
        txtTotalPrice = new org.jdesktop.swingx.JXTextField();
        txtTotalQty = new org.jdesktop.swingx.JXTextField();

        setBackground(new java.awt.Color(166, 176, 176));
        setForeground(new java.awt.Color(153, 153, 153));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Select Date");

        btnRefresh1.setBackground(new java.awt.Color(204, 204, 204));
        btnRefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sareecenter/iconsS/RefreshFrame 1_50px.png"))); // NOI18N
        btnRefresh1.setToolTipText("Reload");
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });

        tblGRNPayments.setForeground(new java.awt.Color(51, 51, 51));
        tblGRNPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Payment Date", "GRN ID", "Total Amount", "Total Qty"
            }
        ));
        tblGRNPayments.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jScrollPane2.setViewportView(tblGRNPayments);

        cmbSelectItem.setBackground(new java.awt.Color(204, 204, 204));
        cmbSelectItem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbSelectItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectItem.setToolTipText("to select Item");
        cmbSelectItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSelectItemItemStateChanged(evt);
            }
        });
        cmbSelectItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectItemActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("View All Supplier Payments");

        cmbSelectType.setBackground(new java.awt.Color(204, 204, 204));
        cmbSelectType.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmbSelectType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectType.setToolTipText("to select type");
        cmbSelectType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSelectTypeItemStateChanged(evt);
            }
        });
        cmbSelectType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSelectType, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSelectItem, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSelectItem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSelectType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        btnCancel1.setForeground(new java.awt.Color(51, 51, 51));
        btnCancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sareecenter/iconsS/Cancel_35px.png"))); // NOI18N
        btnCancel1.setToolTipText("Cleaar all");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 153));
        jLabel18.setText("Total Qty");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("Total Price");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("Supplier Payment ID");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 153));
        jLabel21.setText("Payment Date");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("GRN ID");

        txtGRNPaymentID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtGRNPaymentID.setPrompt("Payment ID");
        txtGRNPaymentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGRNPaymentIDActionPerformed(evt);
            }
        });

        txtGRNPaymentDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtGRNPaymentDate.setPrompt("Payment Date");

        txtGRNID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtGRNID.setPrompt("GRN ID");

        txtTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTotalPrice.setPrompt("Total Price");

        txtTotalQty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTotalQty.setPrompt("Total Qty");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(28, 28, 28)
                        .addComponent(txtGRNPaymentID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalQty, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGRNID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGRNPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtGRNPaymentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtGRNPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGRNID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        try {
            ArrayList<GRNPaymentsDTO> allPayments = GRNPaymentsController.getAllGRNPayments();

            DefaultTableModel dtm = (DefaultTableModel) tblGRNPayments.getModel();

            dtm.setRowCount(0);

            for (GRNPaymentsDTO payment : allPayments) {

                Object[] rowData = {payment.getGrnPID(),
                    payment.getpDate(),
                    payment.getGrnID(),
                    payment.getTotal_price(),
                    payment.getTotal_qty()};

                dtm.addRow(rowData);

            }
        } catch (Exception ex) {
            Logger.getLogger(PanelPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void cmbSelectItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSelectItemItemStateChanged
        try {
            if (cmbSelectItem.getSelectedIndex() == -1) {
                return;
            }
            GRNPaymentsDTO grnPayments = null;
            if (cmbSelectType.getSelectedItem() == "GRN ID") {
                grnPayments = GRNPaymentsController.searchGRNPayments(new GRNPaymentsDTO(null, null, cmbSelectItem.getSelectedItem().toString(), null, 0));

            }
            if (cmbSelectType.getSelectedItem() == "GRN Payment ID") {
                grnPayments = GRNPaymentsController.searchGRNPayments(new GRNPaymentsDTO( cmbSelectItem.getSelectedItem().toString(),null,null, null, 0));
            }
            if (cmbSelectType.getSelectedItem() == "Payment Date") {
                grnPayments = GRNPaymentsController.searchGRNPayments(new GRNPaymentsDTO(null, cmbSelectItem.getSelectedItem().toString(), null, null, 0));
            }

            if (grnPayments == null) {
              System.out.println("A");
                return;

            }

            DefaultTableModel dtm = (DefaultTableModel) tblGRNPayments.getModel();
            dtm.setRowCount(0);
            Object[] rowData = {grnPayments.getGrnPID(),
                grnPayments.getpDate(),
                grnPayments.getGrnID(),
                grnPayments.getTotal_price(),
                grnPayments.getTotal_qty(),};

            dtm.addRow(rowData);

            /*itemDescriptionText.setText(item.getDescription());
            qtyOnHandText.setText(item.getQtyOnHand() + "");
            itemPriceText.setText(item.getUnitPrice().toPlainString());*/
        } catch (Exception ex) {
            Logger.getLogger(PanelCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbSelectItemItemStateChanged

    private void cmbSelectItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSelectItemActionPerformed

    private void cmbSelectTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSelectTypeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSelectTypeItemStateChanged

    private void cmbSelectTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSelectTypeActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void txtGRNPaymentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGRNPaymentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGRNPaymentIDActionPerformed

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
//        getID();
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JComboBox<String> cmbSelectItem;
    private javax.swing.JComboBox<String> cmbSelectType;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable tblGRNPayments;
    private org.jdesktop.swingx.JXTextField txtGRNID;
    private org.jdesktop.swingx.JXTextField txtGRNPaymentDate;
    private org.jdesktop.swingx.JXTextField txtGRNPaymentID;
    private org.jdesktop.swingx.JXTextField txtTotalPrice;
    private org.jdesktop.swingx.JXTextField txtTotalQty;
    // End of variables declaration//GEN-END:variables
}
