/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.sareecenter.view;

/**
 *
 * @author User
 */
public class SelectionPanelGRN extends javax.swing.JPanel {

    /**
     * Creates new form panelItem
     */
    public SelectionPanelGRN() {
        initComponents();
        subPanelGRN.setVisible(false);
        subPanelGRNDetails.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnGRN = new javax.swing.JButton();
        btnGRNDetails = new javax.swing.JButton();
        subPanelGRN = new javax.swing.JPanel();
        btnAddGRN = new javax.swing.JButton();
        btnSearchGRN = new javax.swing.JButton();
        btnUpdateGRN = new javax.swing.JButton();
        btnRemoveGRN = new javax.swing.JButton();
        btnViewAlGRNs = new javax.swing.JButton();
        subPanelGRNDetails = new javax.swing.JPanel();
        btnAddGRNDetails = new javax.swing.JButton();
        btnSearchGRNDetails = new javax.swing.JButton();
        btnUpdateGRNDetails = new javax.swing.JButton();
        btnRemoveGRNDetails = new javax.swing.JButton();
        btnViewAllGRNDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGRN.setBackground(new java.awt.Color(255, 255, 255));
        btnGRN.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        btnGRN.setForeground(new java.awt.Color(0, 153, 153));
        btnGRN.setText("GRN");
        btnGRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGRNActionPerformed(evt);
            }
        });
        jPanel6.add(btnGRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 100));

        btnGRNDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnGRNDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGRNDetails.setForeground(new java.awt.Color(0, 153, 153));
        btnGRNDetails.setText("GRN Details");
        btnGRNDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGRNDetailsActionPerformed(evt);
            }
        });
        jPanel6.add(btnGRNDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 180, 100));

        subPanelGRN.setBackground(new java.awt.Color(0, 153, 153));
        subPanelGRN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddGRN.setBackground(new java.awt.Color(255, 255, 255));
        btnAddGRN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddGRN.setForeground(new java.awt.Color(0, 153, 153));
        btnAddGRN.setText("Add GRN");
        btnAddGRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGRNActionPerformed(evt);
            }
        });
        subPanelGRN.add(btnAddGRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 290, -1));

        btnSearchGRN.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchGRN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSearchGRN.setForeground(new java.awt.Color(0, 153, 153));
        btnSearchGRN.setText("Search GRN");
        btnSearchGRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchGRNActionPerformed(evt);
            }
        });
        subPanelGRN.add(btnSearchGRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, -1));

        btnUpdateGRN.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateGRN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnUpdateGRN.setForeground(new java.awt.Color(0, 153, 153));
        btnUpdateGRN.setText("Update GRN");
        btnUpdateGRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateGRNActionPerformed(evt);
            }
        });
        subPanelGRN.add(btnUpdateGRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 290, -1));

        btnRemoveGRN.setBackground(new java.awt.Color(255, 255, 255));
        btnRemoveGRN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemoveGRN.setForeground(new java.awt.Color(0, 153, 153));
        btnRemoveGRN.setText("Remove GRN");
        btnRemoveGRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveGRNActionPerformed(evt);
            }
        });
        subPanelGRN.add(btnRemoveGRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 290, -1));

        btnViewAlGRNs.setBackground(new java.awt.Color(255, 255, 255));
        btnViewAlGRNs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnViewAlGRNs.setForeground(new java.awt.Color(0, 153, 153));
        btnViewAlGRNs.setText("View All GRNs");
        btnViewAlGRNs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAlGRNsActionPerformed(evt);
            }
        });
        subPanelGRN.add(btnViewAlGRNs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 290, -1));

        jPanel6.add(subPanelGRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 344, 417));

        subPanelGRNDetails.setBackground(new java.awt.Color(0, 153, 153));
        subPanelGRNDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddGRNDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnAddGRNDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddGRNDetails.setForeground(new java.awt.Color(0, 153, 153));
        btnAddGRNDetails.setText("Add GRN Details");
        btnAddGRNDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGRNDetailsActionPerformed(evt);
            }
        });
        subPanelGRNDetails.add(btnAddGRNDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 270, -1));

        btnSearchGRNDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchGRNDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSearchGRNDetails.setForeground(new java.awt.Color(0, 153, 153));
        btnSearchGRNDetails.setText("Search GRN Details");
        btnSearchGRNDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchGRNDetailsActionPerformed(evt);
            }
        });
        subPanelGRNDetails.add(btnSearchGRNDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 270, -1));

        btnUpdateGRNDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateGRNDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnUpdateGRNDetails.setForeground(new java.awt.Color(0, 153, 153));
        btnUpdateGRNDetails.setText("Update GRN Details");
        btnUpdateGRNDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateGRNDetailsActionPerformed(evt);
            }
        });
        subPanelGRNDetails.add(btnUpdateGRNDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, -1));

        btnRemoveGRNDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnRemoveGRNDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemoveGRNDetails.setForeground(new java.awt.Color(0, 153, 153));
        btnRemoveGRNDetails.setText("Remove GRN Details");
        btnRemoveGRNDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveGRNDetailsActionPerformed(evt);
            }
        });
        subPanelGRNDetails.add(btnRemoveGRNDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 270, -1));

        btnViewAllGRNDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnViewAllGRNDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnViewAllGRNDetails.setForeground(new java.awt.Color(0, 153, 153));
        btnViewAllGRNDetails.setText("View All GRN Details");
        btnViewAllGRNDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllGRNDetailsActionPerformed(evt);
            }
        });
        subPanelGRNDetails.add(btnViewAllGRNDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 270, -1));

        jPanel6.add(subPanelGRNDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 344, 417));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 370, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGRNDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGRNDetailsActionPerformed
        subPanelGRN.setVisible(false);
        subPanelGRNDetails.setVisible(true);
        HomePage.pnlMain.removeAll();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnGRNDetailsActionPerformed

    private void btnSearchGRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchGRNActionPerformed
        PanelGRN panelGRN = new PanelGRN();
        HomePage.pnlMain.removeAll();
        panelGRN.setSize(HomePage.pnlMain.getSize());
        panelGRN.setVisible(true);
        HomePage.pnlMain.add(panelGRN);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnSearchGRNActionPerformed

    private void btnGRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGRNActionPerformed
        subPanelGRN.setVisible(true);
        subPanelGRNDetails.setVisible(false);
        HomePage.pnlMain.removeAll();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnGRNActionPerformed

    private void btnSearchGRNDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchGRNDetailsActionPerformed
        PanelGRNDetails panelGRNDetails = new PanelGRNDetails();
        HomePage.pnlMain.removeAll();
        panelGRNDetails.setSize(HomePage.pnlMain.getSize());
        panelGRNDetails.setVisible(true);
        HomePage.pnlMain.add(panelGRNDetails);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnSearchGRNDetailsActionPerformed

    private void btnViewAlGRNsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAlGRNsActionPerformed
        PanelGRN panelGRN = new PanelGRN();
        HomePage.pnlMain.removeAll();
        panelGRN.setSize(HomePage.pnlMain.getSize());
        panelGRN.setVisible(true);
        HomePage.pnlMain.add(panelGRN);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnViewAlGRNsActionPerformed

    private void btnRemoveGRNDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveGRNDetailsActionPerformed
        PanelGRNDetails panelGRNDetails = new PanelGRNDetails();
        HomePage.pnlMain.removeAll();
        panelGRNDetails.setSize(HomePage.pnlMain.getSize());
        panelGRNDetails.setVisible(true);
        HomePage.pnlMain.add(panelGRNDetails);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnRemoveGRNDetailsActionPerformed

    private void btnUpdateGRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateGRNActionPerformed
        PanelGRN panelGRN = new PanelGRN();
        HomePage.pnlMain.removeAll();
        panelGRN.setSize(HomePage.pnlMain.getSize());
        panelGRN.setVisible(true);
        HomePage.pnlMain.add(panelGRN);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnUpdateGRNActionPerformed

    private void btnAddGRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGRNActionPerformed
        PanelGRN panelGRN = new PanelGRN();
        HomePage.pnlMain.removeAll();
        panelGRN.setSize(HomePage.pnlMain.getSize());
        panelGRN.setVisible(true);
        HomePage.pnlMain.add(panelGRN);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnAddGRNActionPerformed

    private void btnRemoveGRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveGRNActionPerformed
        PanelGRN panelGRN = new PanelGRN();
        HomePage.pnlMain.removeAll();
        panelGRN.setSize(HomePage.pnlMain.getSize());
        panelGRN.setVisible(true);
        HomePage.pnlMain.add(panelGRN);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnRemoveGRNActionPerformed

    private void btnAddGRNDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGRNDetailsActionPerformed
        PanelGRNDetails panelGRNDetails = new PanelGRNDetails();
        HomePage.pnlMain.removeAll();
        panelGRNDetails.setSize(HomePage.pnlMain.getSize());
        panelGRNDetails.setVisible(true);
        HomePage.pnlMain.add(panelGRNDetails);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();

    }//GEN-LAST:event_btnAddGRNDetailsActionPerformed

    private void btnUpdateGRNDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateGRNDetailsActionPerformed
        PanelGRNDetails panelGRNDetails = new PanelGRNDetails();
        HomePage.pnlMain.removeAll();
        panelGRNDetails.setSize(HomePage.pnlMain.getSize());
        panelGRNDetails.setVisible(true);
        HomePage.pnlMain.add(panelGRNDetails);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();

    }//GEN-LAST:event_btnUpdateGRNDetailsActionPerformed

    private void btnViewAllGRNDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllGRNDetailsActionPerformed
        PanelGRNDetails panelGRNDetails = new PanelGRNDetails();
        HomePage.pnlMain.removeAll();
        panelGRNDetails.setSize(HomePage.pnlMain.getSize());
        panelGRNDetails.setVisible(true);
        HomePage.pnlMain.add(panelGRNDetails);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();

    }//GEN-LAST:event_btnViewAllGRNDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGRN;
    private javax.swing.JButton btnAddGRNDetails;
    private javax.swing.JButton btnGRN;
    private javax.swing.JButton btnGRNDetails;
    private javax.swing.JButton btnRemoveGRN;
    private javax.swing.JButton btnRemoveGRNDetails;
    private javax.swing.JButton btnSearchGRN;
    private javax.swing.JButton btnSearchGRNDetails;
    private javax.swing.JButton btnUpdateGRN;
    private javax.swing.JButton btnUpdateGRNDetails;
    private javax.swing.JButton btnViewAlGRNs;
    private javax.swing.JButton btnViewAllGRNDetails;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    public static javax.swing.JPanel subPanelGRN;
    public static javax.swing.JPanel subPanelGRNDetails;
    // End of variables declaration//GEN-END:variables
}
