/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.sareecenter.view;

/**
 *
 * @author User
 */
public class SelectionPanelOrders extends javax.swing.JPanel {

    /**
     * Creates new form panelOrders
     */
    public SelectionPanelOrders() {
        initComponents();
        subPanelOrders.setVisible(false);
        subPanelOrders.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnOrders = new javax.swing.JButton();
        btnOrderDetails = new javax.swing.JButton();
        subPanelOrders = new javax.swing.JPanel();
        btnAddOrder = new javax.swing.JButton();
        btnremoveOrder = new javax.swing.JButton();
        btnUpdateOrder = new javax.swing.JButton();
        btnDeleteOrder = new javax.swing.JButton();
        btnViewAllOrders = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrders.setBackground(new java.awt.Color(255, 255, 255));
        btnOrders.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnOrders.setForeground(new java.awt.Color(0, 153, 153));
        btnOrders.setText("Orders");
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });
        jPanel6.add(btnOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 158, 100));

        btnOrderDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnOrderDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnOrderDetails.setForeground(new java.awt.Color(0, 153, 153));
        btnOrderDetails.setText("Order Details");
        btnOrderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDetailsActionPerformed(evt);
            }
        });
        jPanel6.add(btnOrderDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 100));

        subPanelOrders.setBackground(new java.awt.Color(0, 153, 153));
        subPanelOrders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnAddOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddOrder.setForeground(new java.awt.Color(0, 153, 153));
        btnAddOrder.setText("Add Order");
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });
        subPanelOrders.add(btnAddOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 47, 215, -1));

        btnremoveOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnremoveOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnremoveOrder.setForeground(new java.awt.Color(0, 153, 153));
        btnremoveOrder.setText("Remove Order");
        btnremoveOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveOrderActionPerformed(evt);
            }
        });
        subPanelOrders.add(btnremoveOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 116, -1, -1));

        btnUpdateOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnUpdateOrder.setForeground(new java.awt.Color(0, 153, 153));
        btnUpdateOrder.setText("Update Order");
        btnUpdateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrderActionPerformed(evt);
            }
        });
        subPanelOrders.add(btnUpdateOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 189, 215, -1));

        btnDeleteOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDeleteOrder.setForeground(new java.awt.Color(0, 153, 153));
        btnDeleteOrder.setText("Delete Order");
        btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderActionPerformed(evt);
            }
        });
        subPanelOrders.add(btnDeleteOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 261, 215, -1));

        btnViewAllOrders.setBackground(new java.awt.Color(255, 255, 255));
        btnViewAllOrders.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnViewAllOrders.setForeground(new java.awt.Color(0, 153, 153));
        btnViewAllOrders.setText("View All Orders");
        btnViewAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllOrdersActionPerformed(evt);
            }
        });
        subPanelOrders.add(btnViewAllOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 330, 215, -1));

        jPanel6.add(subPanelOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 344, 417));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 370, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDetailsActionPerformed
       
        subPanelOrders.setVisible(false);
        HomePage.pnlMain.removeAll();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnOrderDetailsActionPerformed

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed
        subPanelOrders.setVisible(true);
        subPanelOrders.setVisible(false);
        HomePage.pnlMain.removeAll();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnOrdersActionPerformed

    private void btnremoveOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveOrderActionPerformed
        PanelOrders panelOrders = new PanelOrders();
        HomePage.pnlMain.removeAll();
        panelOrders.setSize(HomePage.pnlMain.getSize());
        panelOrders.setVisible(true);
        HomePage.pnlMain.add(panelOrders);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnremoveOrderActionPerformed

    private void btnUpdateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrderActionPerformed
        PanelOrders panelOrders = new PanelOrders();
        HomePage.pnlMain.removeAll();
        panelOrders.setSize(HomePage.pnlMain.getSize());
        panelOrders.setVisible(true);
        HomePage.pnlMain.add(panelOrders);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnUpdateOrderActionPerformed

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed
        PanelOrders panelOrders = new PanelOrders();
        HomePage.pnlMain.removeAll();
        panelOrders.setSize(HomePage.pnlMain.getSize());
        panelOrders.setVisible(true);
        HomePage.pnlMain.add(panelOrders);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnAddOrderActionPerformed

    private void btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderActionPerformed
        PanelOrders panelOrders = new PanelOrders();
        HomePage.pnlMain.removeAll();
        panelOrders.setSize(HomePage.pnlMain.getSize());
        panelOrders.setVisible(true);
        HomePage.pnlMain.add(panelOrders);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnDeleteOrderActionPerformed

    private void btnViewAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllOrdersActionPerformed
        PanelOrders panelOrders = new PanelOrders();
        HomePage.pnlMain.removeAll();
        panelOrders.setSize(HomePage.pnlMain.getSize());
        panelOrders.setVisible(true);
        HomePage.pnlMain.add(panelOrders);
        HomePage.pnlMain.revalidate();
        HomePage.pnlMain.repaint();
    }//GEN-LAST:event_btnViewAllOrdersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnOrderDetails;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnUpdateOrder;
    private javax.swing.JButton btnViewAllOrders;
    private javax.swing.JButton btnremoveOrder;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    public static javax.swing.JPanel subPanelOrders;
    // End of variables declaration//GEN-END:variables
}
